service: cloud-ticket-backend
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1
  memorySize: 128
  tracing:
    lambda: true
    apiGateway: true
  environment:
    EVENTS_TABLE: ${self:service}-events-table-${sls:stage}
    QUEUE_URL: { Ref: TicketQueue }
    EVENT_BUS_NAME: { Ref: EventBus }
    MEDIA_BUCKET_NAME: ${self:service}-media-${sls:stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
          Resource: "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.EVENTS_TABLE}"
        - Effect: Allow
          Action:
            - sqs:SendMessage
          Resource: { Fn::GetAtt: [TicketQueue, Arn] }
        - Effect: Allow
          Action:
            - xray:PutTraceSegments
            - xray:PutTelemetryRecords
          Resource: "*"
        - Effect: Allow
          Action:
            - events:PutEvents # EventBridge'e olay fırlatma yetkisi
          Resource: { Fn::GetAtt: [EventBus, Arn] }  
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
          Resource: "arn:aws:s3:::${self:provider.environment.MEDIA_BUCKET_NAME}/*"

# --- YENİ NESİL TYPESCRIPT AYARI (Plugin yerine Build) ---
build:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ['aws-sdk']
    target: 'node18'
    platform: 'node'

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get
          cors: true
  createEvent:
    handler: handler.createEvent
    events:
      - http:
          path: /event
          method: post
          cors: true
          authorizer:
            name: PrivateAuthorizer
            type: COGNITO_USER_POOLS
            arn:
              Fn::GetAtt:
                - CognitoUserPool
                - Arn
  processEvent:
    handler: handler.processEvent
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - TicketQueue
              - Arn
          batchSize: 1
  listEvents:
    handler: handler.listEvents
    events:
      - http:
          path: /events
          method: get
          cors: true
  getEvent:
    handler: handler.getEvent
    events:
      - http:
          path: /event/{id}
          method: get
          cors: true
  getUploadUrl:
    handler: handler.getUploadUrl
    events:
      - http:
          path: /upload-url
          method: get
          cors: true
          authorizer:
            name: PrivateAuthorizer
            type: COGNITO_USER_POOLS
            arn:
              Fn::GetAtt:
                - CognitoUserPool
                - Arn

resources:
  Resources:
    EventsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.EVENTS_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    
    TicketQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-queue-${sls:stage}

    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:service}-user-pool-${sls:stage}
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email

    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:service}-user-pool-client-${sls:stage}
        UserPoolId:
          Ref: CognitoUserPool
        GenerateSecret: false
        ExplicitAuthFlows:
          - ALLOW_ADMIN_USER_PASSWORD_AUTH
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
          - ALLOW_USER_SRP_AUTH
    EventBus:
      Type: AWS::Events::EventBus
      Properties:
        Name: ${self:service}-event-bus-${sls:stage}
    EventToSQSRule:
      Type: AWS::Events::Rule
      Properties:
        EventBusName: { Ref: EventBus }
        Description: "Bilet siparişlerini SQS kuyruğuna ilet"
        State: ENABLED
        EventPattern:
          source:
            - "com.cloudticket" # Bizim uydurduğumuz kaynak ismi
          detail-type:
            - "OrderCreated"    # Bizim uydurduğumuz olay tipi
        Targets:
          - Id: "SendToSQS"
            Arn: { Fn::GetAtt: [TicketQueue, Arn] }
    TicketQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - { Ref: TicketQueue }
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: "events.amazonaws.com" # EventBridge servisi
              Action: "sqs:SendMessage"
              Resource: { Fn::GetAtt: [TicketQueue, Arn] }
              Condition:
                ArnEquals:
                  "aws:SourceArn": { Fn::GetAtt: [EventToSQSRule, Arn] }        
    
    MediaBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.MEDIA_BUCKET_NAME}
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - "*"
              AllowedHeaders:
                - "*"
              AllowedMethods:
                - GET
                - PUT
                - POST
                - HEAD
              MaxAge: 3000