Resources:
  EventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.EVENTS_TABLE}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  TicketsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.TICKETS_TABLE}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: ticketId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: ticketId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
