Resources:
  EventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.EVENTS_TABLE}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
